### ISSUE TITLE
希望多多交流

### ISSUE THREAD

**Issue by Remember2015** [Rocaloid/Rocaloid.github.io#4]
rocaloid的小伙伴们，我是APP [走音] 的工作人员。看到你们制作的rocaloid，非常激动。走音本身是给小伙伴们改词做歌用的，当然我们目前做的不太好，合成效果也不够，所以真心希望能够和你们交流合作一下。国内做这块的也太少了。你们的官方邮件无法联络，所以开了issue。不太正式啦，望请谅解~

**Comment by tuxzz** [comment]
你好，我们最近遇到了一些专利问题，或许会需要很长一段时间来研发新的技术。对此我们非常抱歉。感谢贵开发组对我们的关注。
